### ISSUE TITLE
add "Settings" to Plugins page (near "Activate/Deactivate")

### ISSUE THREAD

**Issue by aya2work** [petrows/wp-tg-instantview#1]
Regarding settings - a small tip, it would be good to duplicate them in the list of plugins.  That is, usually (well, I'm so used to it) that plugins with settings under their name in the list of plugins (where Activate/Deactivate) have a link Settings (see the screen) - it would be great to add it there.  Not everyone does this, but a lot of people do, and it is convenient.

**Comment by SamuelRoguez** [comment]
This guy is a genius, he has the most compatible plugin with higher versions right now.
I don't know if the code is vulnerable or not.
That's why I haven't installed it yet.

**Comment by petrows** [comment]
Hey @aya2work , 

I am sorry, i really missed email about this issue opened and answering you now. Thanks a lot for your input, i will check this. I have created my plugin using WP developer guideline, likely they don't propose this option as example for new developers.

Hey @SamuelRoguez ,

You have opened #2 issue with your question, i have answered you there. In short: to publish plugin in the registry you have to pass security checks and code-review, so it was already verified by WP team.

**Comment by petrows** [comment]
Fixed in Version 1.5. Dear @aya2work , please update via Wordpress plugin manager or using Github releases.
