### ISSUE TITLE
So far the most up to date plugin of all

### ISSUE THREAD

**Issue by SamuelRoguez** [petrows/wp-tg-instantview#2]
I don't quite understand why your plugin has no reviews, and why it's not verified by WordPress.
Do you have any way to verify it by WordPress?
You are currently the only one giving instant view functionality in Telegram, and that's a big plus.
But I would like WP to give the OK somehow.
At the moment you just need a security check on the code, or something that proves it's not vulnerable.

**Comment by petrows** [comment]
Hey @SamuelRoguez , 

Wordpress do not allow to publish plugin in Registry without long-lasting security check and code review. 

I have spend ~3 months to pass this checks and publish it in the registry, you may find it here: https://wordpress.org/plugins/tg-instantview/

So, i'd say that it already was verified by WP team. If you know any way request more, please let me know.

**Comment by petrows** [comment]
Just found out that this information is actually missing in project README. I have updated it, thanks for finding!

**Comment by petrows** [comment]
I hope it clarifies your concerns here, if not - please let me know.
